name: CI

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build & test with Maven
        run: mvn -B verify

      - name: Upload JAR
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ancMobileOS-jar
          path: target/*.jar
